/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.SearchParams;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BreadCrumbTrailItem
 */
public class BreadCrumbTrailItemTest {
    private final BreadCrumbTrailItem model = new BreadCrumbTrailItem();

    /**
     * Model tests for BreadCrumbTrailItem
     */
    @Test
    public void testBreadCrumbTrailItem() {
        // TODO: test BreadCrumbTrailItem
    }

    /**
     * Test the property 'associatedFieldName'
     */
    @Test
    public void associatedFieldNameTest() {
        // TODO: test associatedFieldName
    }

    /**
     * Test the property 'searchParams'
     */
    @Test
    public void searchParamsTest() {
        // TODO: test searchParams
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
