/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.FeedbackText;
import de.factfinder.client.model.Question;
import de.factfinder.client.model.Target;
import de.factfinder.client.model.TypedFlatRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Campaign
 */
public class CampaignTest {
    private final Campaign model = new Campaign();

    /**
     * Model tests for Campaign
     */
    @Test
    public void testCampaign() {
        // TODO: test Campaign
    }

    /**
     * Test the property 'activeQuestions'
     */
    @Test
    public void activeQuestionsTest() {
        // TODO: test activeQuestions
    }

    /**
     * Test the property 'advisorTree'
     */
    @Test
    public void advisorTreeTest() {
        // TODO: test advisorTree
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'excludeProductsNotInMarkets'
     */
    @Test
    public void excludeProductsNotInMarketsTest() {
        // TODO: test excludeProductsNotInMarkets
    }

    /**
     * Test the property 'excludeProductsNotInRange'
     */
    @Test
    public void excludeProductsNotInRangeTest() {
        // TODO: test excludeProductsNotInRange
    }

    /**
     * Test the property 'feedbackTexts'
     */
    @Test
    public void feedbackTextsTest() {
        // TODO: test feedbackTexts
    }

    /**
     * Test the property 'flavour'
     */
    @Test
    public void flavourTest() {
        // TODO: test flavour
    }

    /**
     * Test the property 'hits'
     */
    @Test
    public void hitsTest() {
        // TODO: test hits
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

}
