/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.Campaign;
import de.factfinder.client.model.RecommendationResult;
import de.factfinder.client.model.RecordWithId;
import de.factfinder.client.model.SimilarProducts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DetailPage
 */
public class DetailPageTest {
    private final DetailPage model = new DetailPage();

    /**
     * Model tests for DetailPage
     */
    @Test
    public void testDetailPage() {
        // TODO: test DetailPage
    }

    /**
     * Test the property 'campaigns'
     */
    @Test
    public void campaignsTest() {
        // TODO: test campaigns
    }

    /**
     * Test the property 'fieldRoles'
     */
    @Test
    public void fieldRolesTest() {
        // TODO: test fieldRoles
    }

    /**
     * Test the property 'recommendations'
     */
    @Test
    public void recommendationsTest() {
        // TODO: test recommendations
    }

    /**
     * Test the property 'record'
     */
    @Test
    public void recordTest() {
        // TODO: test record
    }

    /**
     * Test the property 'similarProducts'
     */
    @Test
    public void similarProductsTest() {
        // TODO: test similarProducts
    }

}
