/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ImportChannelResult
 */
public class ImportChannelResultTest {
    private final ImportChannelResult model = new ImportChannelResult();

    /**
     * Model tests for ImportChannelResult
     */
    @Test
    public void testImportChannelResult() {
        // TODO: test ImportChannelResult
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'durationInSeconds'
     */
    @Test
    public void durationInSecondsTest() {
        // TODO: test durationInSeconds
    }

    /**
     * Test the property 'errorMessages'
     */
    @Test
    public void errorMessagesTest() {
        // TODO: test errorMessages
    }

    /**
     * Test the property 'importType'
     */
    @Test
    public void importTypeTest() {
        // TODO: test importType
    }

    /**
     * Test the property 'importedFields'
     */
    @Test
    public void importedFieldsTest() {
        // TODO: test importedFields
    }

    /**
     * Test the property 'importedRecords'
     */
    @Test
    public void importedRecordsTest() {
        // TODO: test importedRecords
    }

    /**
     * Test the property 'importedWorldmatchDocuments'
     */
    @Test
    public void importedWorldmatchDocumentsTest() {
        // TODO: test importedWorldmatchDocuments
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'statusMessages'
     */
    @Test
    public void statusMessagesTest() {
        // TODO: test statusMessages
    }

}
