/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PredBasketClickEvent
 */
public class PredBasketClickEventTest {
    private final PredBasketClickEvent model = new PredBasketClickEvent();

    /**
     * Model tests for PredBasketClickEvent
     */
    @Test
    public void testPredBasketClickEvent() {
        // TODO: test PredBasketClickEvent
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'masterId'
     */
    @Test
    public void masterIdTest() {
        // TODO: test masterId
    }

    /**
     * Test the property 'purchaserId'
     */
    @Test
    public void purchaserIdTest() {
        // TODO: test purchaserId
    }

    /**
     * Test the property 'sid'
     */
    @Test
    public void sidTest() {
        // TODO: test sid
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
