/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.Answer;
import de.factfinder.client.model.BreadCrumbTrailItem;
import de.factfinder.client.model.Campaign;
import de.factfinder.client.model.DescribedSortItem;
import de.factfinder.client.model.Facet;
import de.factfinder.client.model.Filter;
import de.factfinder.client.model.Geo;
import de.factfinder.client.model.Paging;
import de.factfinder.client.model.SearchControlParams;
import de.factfinder.client.model.SearchParams;
import de.factfinder.client.model.SearchRecord;
import de.factfinder.client.model.SingleWordSearchResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Result
 */
public class ResultTest {
    private final Result model = new Result();

    /**
     * Model tests for Result
     */
    @Test
    public void testResult() {
        // TODO: test Result
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

    /**
     * Test the property 'articleNumberSearch'
     */
    @Test
    public void articleNumberSearchTest() {
        // TODO: test articleNumberSearch
    }

    /**
     * Test the property 'breadCrumbTrail'
     */
    @Test
    public void breadCrumbTrailTest() {
        // TODO: test breadCrumbTrail
    }

    /**
     * Test the property 'campaigns'
     */
    @Test
    public void campaignsTest() {
        // TODO: test campaigns
    }

    /**
     * Test the property 'facets'
     */
    @Test
    public void facetsTest() {
        // TODO: test facets
    }

    /**
     * Test the property 'fieldRoles'
     */
    @Test
    public void fieldRolesTest() {
        // TODO: test fieldRoles
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'followSearch'
     */
    @Test
    public void followSearchTest() {
        // TODO: test followSearch
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

    /**
     * Test the property 'hits'
     */
    @Test
    public void hitsTest() {
        // TODO: test hits
    }

    /**
     * Test the property 'paging'
     */
    @Test
    public void pagingTest() {
        // TODO: test paging
    }

    /**
     * Test the property 'scoreFirstHit'
     */
    @Test
    public void scoreFirstHitTest() {
        // TODO: test scoreFirstHit
    }

    /**
     * Test the property 'scoreLastHit'
     */
    @Test
    public void scoreLastHitTest() {
        // TODO: test scoreLastHit
    }

    /**
     * Test the property 'searchControlParams'
     */
    @Test
    public void searchControlParamsTest() {
        // TODO: test searchControlParams
    }

    /**
     * Test the property 'searchParams'
     */
    @Test
    public void searchParamsTest() {
        // TODO: test searchParams
    }

    /**
     * Test the property 'singleWordResults'
     */
    @Test
    public void singleWordResultsTest() {
        // TODO: test singleWordResults
    }

    /**
     * Test the property 'sortItems'
     */
    @Test
    public void sortItemsTest() {
        // TODO: test sortItems
    }

    /**
     * Test the property 'timedOut'
     */
    @Test
    public void timedOutTest() {
        // TODO: test timedOut
    }

    /**
     * Test the property 'tookTotal'
     */
    @Test
    public void tookTotalTest() {
        // TODO: test tookTotal
    }

    /**
     * Test the property 'tookWorldmatch'
     */
    @Test
    public void tookWorldmatchTest() {
        // TODO: test tookWorldmatch
    }

    /**
     * Test the property 'totalHits'
     */
    @Test
    public void totalHitsTest() {
        // TODO: test totalHits
    }

}
