/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.AdvisorCampaignStatusHolder;
import de.factfinder.client.model.CustomParameter;
import de.factfinder.client.model.Filter;
import de.factfinder.client.model.Location;
import de.factfinder.client.model.SortItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SuggestParams
 */
public class SuggestParamsTest {
    private final SuggestParams model = new SuggestParams();

    /**
     * Model tests for SuggestParams
     */
    @Test
    public void testSuggestParams() {
        // TODO: test SuggestParams
    }

    /**
     * Test the property 'activeAbTests'
     */
    @Test
    public void activeAbTestsTest() {
        // TODO: test activeAbTests
    }

    /**
     * Test the property 'advisorStatus'
     */
    @Test
    public void advisorStatusTest() {
        // TODO: test advisorStatus
    }

    /**
     * Test the property 'articleNumberSearch'
     */
    @Test
    public void articleNumberSearchTest() {
        // TODO: test articleNumberSearch
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'customParameters'
     */
    @Test
    public void customParametersTest() {
        // TODO: test customParameters
    }

    /**
     * Test the property 'excludeProductsNotInRange'
     */
    @Test
    public void excludeProductsNotInRangeTest() {
        // TODO: test excludeProductsNotInRange
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'followSearch'
     */
    @Test
    public void followSearchTest() {
        // TODO: test followSearch
    }

    /**
     * Test the property 'hitsPerPage'
     */
    @Test
    public void hitsPerPageTest() {
        // TODO: test hitsPerPage
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'marketIds'
     */
    @Test
    public void marketIdsTest() {
        // TODO: test marketIds
    }

    /**
     * Test the property 'maxCountVariants'
     */
    @Test
    public void maxCountVariantsTest() {
        // TODO: test maxCountVariants
    }

    /**
     * Test the property 'maxDistance'
     */
    @Test
    public void maxDistanceTest() {
        // TODO: test maxDistance
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'purchaserId'
     */
    @Test
    public void purchaserIdTest() {
        // TODO: test purchaserId
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'searchField'
     */
    @Test
    public void searchFieldTest() {
        // TODO: test searchField
    }

    /**
     * Test the property 'sid'
     */
    @Test
    public void sidTest() {
        // TODO: test sid
    }

    /**
     * Test the property 'sortItems'
     */
    @Test
    public void sortItemsTest() {
        // TODO: test sortItems
    }

}
