/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.Geo;
import de.factfinder.client.model.ResultSuggestion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SuggestionResult
 */
public class SuggestionResultTest {
    private final SuggestionResult model = new SuggestionResult();

    /**
     * Model tests for SuggestionResult
     */
    @Test
    public void testSuggestionResult() {
        // TODO: test SuggestionResult
    }

    /**
     * Test the property 'articleNumberSearchAllowed'
     */
    @Test
    public void articleNumberSearchAllowedTest() {
        // TODO: test articleNumberSearchAllowed
    }

    /**
     * Test the property 'fieldRoles'
     */
    @Test
    public void fieldRolesTest() {
        // TODO: test fieldRoles
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

}
