/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UiSettings
 */
public class UiSettingsTest {
    private final UiSettings model = new UiSettings();

    /**
     * Model tests for UiSettings
     */
    @Test
    public void testUiSettings() {
        // TODO: test UiSettings
    }

    /**
     * Test the property 'enableAdvancedMode'
     */
    @Test
    public void enableAdvancedModeTest() {
        // TODO: test enableAdvancedMode
    }

    /**
     * Test the property 'hideErrorNotifications'
     */
    @Test
    public void hideErrorNotificationsTest() {
        // TODO: test hideErrorNotifications
    }

    /**
     * Test the property 'hideInactiveModules'
     */
    @Test
    public void hideInactiveModulesTest() {
        // TODO: test hideInactiveModules
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

}
