/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.api;

import de.factfinder.client.ApiException;
import de.factfinder.client.model.ApiError;
import de.factfinder.client.model.Campaign;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignApi
 */
@Ignore
public class CampaignApiTest {

    private final CampaignApi api = new CampaignApi();

    
    /**
     * Get page campaigns
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPageCampaignsUsingGETTest() throws ApiException {
        String channel = null;
        String pageId = null;
        Boolean idsOnly = null;
        String sid = null;
        String advisorStatus = null;
        List<Campaign> response = api.getPageCampaignsUsingGET(channel, pageId, idsOnly, sid, advisorStatus);

        // TODO: test validations
    }
    
    /**
     * Get product campaigns
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductCampaignsUsingGETTest() throws ApiException {
        String channel = null;
        String productNumber = null;
        Boolean idsOnly = null;
        String sid = null;
        String advisorStatus = null;
        List<Campaign> response = api.getProductCampaignsUsingGET(channel, productNumber, idsOnly, sid, advisorStatus);

        // TODO: test validations
    }
    
    /**
     * Get shopping cart campaigns
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getShoppingCartCampaignsUsingGETTest() throws ApiException {
        String channel = null;
        List<String> productNumber = null;
        Boolean idsOnly = null;
        String sid = null;
        String advisorStatus = null;
        List<Campaign> response = api.getShoppingCartCampaignsUsingGET(channel, productNumber, idsOnly, sid, advisorStatus);

        // TODO: test validations
    }
    
}
