/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.api;

import de.factfinder.client.ApiException;
import de.factfinder.client.model.ApiError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManagementApi
 */
@Ignore
public class ManagementApiTest {

    private final ManagementApi api = new ManagementApi();

    
    /**
     * Execute whatshot import(s)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importWhatsHotUsingPOSTTest() throws ApiException {
        List<String> channel = null;
        Boolean sendNotifications = null;
        api.importWhatsHotUsingPOST(channel, sendNotifications);

        // TODO: test validations
    }
    
    /**
     * Reload the configuration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void reloadConfigurationUsingPOSTTest() throws ApiException {
        List<String> channel = null;
        api.reloadConfigurationUsingPOST(channel);

        // TODO: test validations
    }
    
}
