/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.api;

import de.factfinder.client.ApiException;
import de.factfinder.client.model.ApiError;
import de.factfinder.client.model.RecommendationResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecommendationApi
 */
@Ignore
public class RecommendationApiTest {

    private final RecommendationApi api = new RecommendationApi();

    
    /**
     * Get recommendations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRecommendationUsingGETTest() throws ApiException {
        String channel = null;
        List<String> id = null;
        Integer maxResults = null;
        String sid = null;
        Boolean idsOnly = null;
        Boolean usePersonalization = null;
        RecommendationResult response = api.getRecommendationUsingGET(channel, id, maxResults, sid, idsOnly, usePersonalization);

        // TODO: test validations
    }
    
}
