/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.api;

import de.factfinder.client.ApiException;
import de.factfinder.client.model.ApiError;
import de.factfinder.client.model.SimilarProducts;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SimilarproductsApi
 */
@Ignore
public class SimilarproductsApiTest {

    private final SimilarproductsApi api = new SimilarproductsApi();

    
    /**
     * Get similar products
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSimilarProductsUsingGETTest() throws ApiException {
        String channel = null;
        String id = null;
        Boolean idsOnly = null;
        Integer maxResults = null;
        SimilarProducts response = api.getSimilarProductsUsingGET(channel, id, idsOnly, maxResults);

        // TODO: test validations
    }
    
}
