/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.api;

import de.factfinder.client.ApiException;
import de.factfinder.client.model.ApiError;
import de.factfinder.client.model.TagCloudEntry;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagcloudApi
 */
@Ignore
public class TagcloudApiTest {

    private final TagcloudApi api = new TagcloudApi();

    
    /**
     * Get tag cloud entries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagCloudUsingGETTest() throws ApiException {
        String channel = null;
        Integer wordCount = null;
        List<TagCloudEntry> response = api.getTagCloudUsingGET(channel, wordCount);

        // TODO: test validations
    }
    
}
