/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AdvisorCampaignStatusHolder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-14T06:49:07.742+02:00")
public class AdvisorCampaignStatusHolder {
  @SerializedName("answerPath")
  private String answerPath = null;

  @SerializedName("campaignId")
  private String campaignId = null;

  public AdvisorCampaignStatusHolder answerPath(String answerPath) {
    this.answerPath = answerPath;
    return this;
  }

   /**
   * Get answerPath
   * @return answerPath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAnswerPath() {
    return answerPath;
  }

  public void setAnswerPath(String answerPath) {
    this.answerPath = answerPath;
  }

  public AdvisorCampaignStatusHolder campaignId(String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvisorCampaignStatusHolder advisorCampaignStatusHolder = (AdvisorCampaignStatusHolder) o;
    return Objects.equals(this.answerPath, advisorCampaignStatusHolder.answerPath) &&
        Objects.equals(this.campaignId, advisorCampaignStatusHolder.campaignId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answerPath, campaignId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvisorCampaignStatusHolder {\n");
    
    sb.append("    answerPath: ").append(toIndentedString(answerPath)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

