/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FilterValue;
import java.util.ArrayList;
import java.util.List;

/**
 * Filter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-14T06:49:07.742+02:00")
public class Filter {
  @SerializedName("name")
  private String name = null;

  @SerializedName("substring")
  private Boolean substring = null;

  @SerializedName("valueList")
  private List<FilterValue> valueList = new ArrayList<FilterValue>();

  public Filter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Filter substring(Boolean substring) {
    this.substring = substring;
    return this;
  }

   /**
   * Get substring
   * @return substring
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSubstring() {
    return substring;
  }

  public void setSubstring(Boolean substring) {
    this.substring = substring;
  }

  public Filter valueList(List<FilterValue> valueList) {
    this.valueList = valueList;
    return this;
  }

  public Filter addValueListItem(FilterValue valueListItem) {
    this.valueList.add(valueListItem);
    return this;
  }

   /**
   * Get valueList
   * @return valueList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FilterValue> getValueList() {
    return valueList;
  }

  public void setValueList(List<FilterValue> valueList) {
    this.valueList = valueList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Filter filter = (Filter) o;
    return Objects.equals(this.name, filter.name) &&
        Objects.equals(this.substring, filter.substring) &&
        Objects.equals(this.valueList, filter.valueList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, substring, valueList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Filter {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    substring: ").append(toIndentedString(substring)).append("\n");
    sb.append("    valueList: ").append(toIndentedString(valueList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

