/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RecordWithId;
import java.util.ArrayList;
import java.util.List;

/**
 * RecommendationResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-14T06:49:07.742+02:00")
public class RecommendationResult {
  @SerializedName("resultRecords")
  private List<RecordWithId> resultRecords = new ArrayList<RecordWithId>();

  @SerializedName("timedOut")
  private Boolean timedOut = null;

  public RecommendationResult resultRecords(List<RecordWithId> resultRecords) {
    this.resultRecords = resultRecords;
    return this;
  }

  public RecommendationResult addResultRecordsItem(RecordWithId resultRecordsItem) {
    this.resultRecords.add(resultRecordsItem);
    return this;
  }

   /**
   * Get resultRecords
   * @return resultRecords
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<RecordWithId> getResultRecords() {
    return resultRecords;
  }

  public void setResultRecords(List<RecordWithId> resultRecords) {
    this.resultRecords = resultRecords;
  }

  public RecommendationResult timedOut(Boolean timedOut) {
    this.timedOut = timedOut;
    return this;
  }

   /**
   * Get timedOut
   * @return timedOut
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getTimedOut() {
    return timedOut;
  }

  public void setTimedOut(Boolean timedOut) {
    this.timedOut = timedOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationResult recommendationResult = (RecommendationResult) o;
    return Objects.equals(this.resultRecords, recommendationResult.resultRecords) &&
        Objects.equals(this.timedOut, recommendationResult.timedOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultRecords, timedOut);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationResult {\n");
    
    sb.append("    resultRecords: ").append(toIndentedString(resultRecords)).append("\n");
    sb.append("    timedOut: ").append(toIndentedString(timedOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

