/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.ApiError;
import io.swagger.client.model.ImportResult;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ImportApi {
    private ApiClient apiClient;

    public ImportApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ImportApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for startRecommendationImportUsingPOST */
    private com.squareup.okhttp.Call startRecommendationImportUsingPOSTCall(List<String> channel, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v1/import/recommendation".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (channel != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "channel", channel));
        if (quiet != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "quiet", quiet));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call startRecommendationImportUsingPOSTValidateBeforeCall(List<String> channel, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = startRecommendationImportUsingPOSTCall(channel, quiet, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Start recommendation import
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ImportResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ImportResult startRecommendationImportUsingPOST(List<String> channel, Boolean quiet) throws ApiException {
        ApiResponse<ImportResult> resp = startRecommendationImportUsingPOSTWithHttpInfo(channel, quiet);
        return resp.getData();
    }

    /**
     * Start recommendation import
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ApiResponse&lt;ImportResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ImportResult> startRecommendationImportUsingPOSTWithHttpInfo(List<String> channel, Boolean quiet) throws ApiException {
        com.squareup.okhttp.Call call = startRecommendationImportUsingPOSTValidateBeforeCall(channel, quiet, null, null);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Start recommendation import (asynchronously)
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call startRecommendationImportUsingPOSTAsync(List<String> channel, Boolean quiet, final ApiCallback<ImportResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = startRecommendationImportUsingPOSTValidateBeforeCall(channel, quiet, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for startSearchImportUsingPOST */
    private com.squareup.okhttp.Call startSearchImportUsingPOSTCall(List<String> channel, Boolean download, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v1/import/search".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (channel != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "channel", channel));
        if (download != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "download", download));
        if (quiet != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "quiet", quiet));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call startSearchImportUsingPOSTValidateBeforeCall(List<String> channel, Boolean download, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = startSearchImportUsingPOSTCall(channel, download, quiet, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Start search import
     * 
     * @param channel channel (optional)
     * @param download if true: causes the import file to be updated first. If no URL is stored in the FACT-Finder configuration, this parameter has no effect. (optional, default to false)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ImportResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ImportResult startSearchImportUsingPOST(List<String> channel, Boolean download, Boolean quiet) throws ApiException {
        ApiResponse<ImportResult> resp = startSearchImportUsingPOSTWithHttpInfo(channel, download, quiet);
        return resp.getData();
    }

    /**
     * Start search import
     * 
     * @param channel channel (optional)
     * @param download if true: causes the import file to be updated first. If no URL is stored in the FACT-Finder configuration, this parameter has no effect. (optional, default to false)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ApiResponse&lt;ImportResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ImportResult> startSearchImportUsingPOSTWithHttpInfo(List<String> channel, Boolean download, Boolean quiet) throws ApiException {
        com.squareup.okhttp.Call call = startSearchImportUsingPOSTValidateBeforeCall(channel, download, quiet, null, null);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Start search import (asynchronously)
     * 
     * @param channel channel (optional)
     * @param download if true: causes the import file to be updated first. If no URL is stored in the FACT-Finder configuration, this parameter has no effect. (optional, default to false)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call startSearchImportUsingPOSTAsync(List<String> channel, Boolean download, Boolean quiet, final ApiCallback<ImportResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = startSearchImportUsingPOSTValidateBeforeCall(channel, download, quiet, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for startSuggestImportUsingPOST */
    private com.squareup.okhttp.Call startSuggestImportUsingPOSTCall(List<String> channel, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/v1/import/suggest".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (channel != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "channel", channel));
        if (quiet != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "quiet", quiet));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call startSuggestImportUsingPOSTValidateBeforeCall(List<String> channel, Boolean quiet, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = startSuggestImportUsingPOSTCall(channel, quiet, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Start suggest import
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ImportResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ImportResult startSuggestImportUsingPOST(List<String> channel, Boolean quiet) throws ApiException {
        ApiResponse<ImportResult> resp = startSuggestImportUsingPOSTWithHttpInfo(channel, quiet);
        return resp.getData();
    }

    /**
     * Start suggest import
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @return ApiResponse&lt;ImportResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ImportResult> startSuggestImportUsingPOSTWithHttpInfo(List<String> channel, Boolean quiet) throws ApiException {
        com.squareup.okhttp.Call call = startSuggestImportUsingPOSTValidateBeforeCall(channel, quiet, null, null);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Start suggest import (asynchronously)
     * 
     * @param channel channel (optional)
     * @param quiet if true: only receive a filled response if an error occurs during the import otherwise the response is just empty (optional, default to false)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call startSuggestImportUsingPOSTAsync(List<String> channel, Boolean quiet, final ApiCallback<ImportResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = startSuggestImportUsingPOSTValidateBeforeCall(channel, quiet, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ImportResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
