/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeleteMarketRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeleteMarketRequest {
  public static final String SERIALIZED_NAME_MARKET_IDS = "marketIds";
  @SerializedName(SERIALIZED_NAME_MARKET_IDS)
  private List<String> marketIds = null;


  public DeleteMarketRequest marketIds(List<String> marketIds) {
    
    this.marketIds = marketIds;
    return this;
  }

  public DeleteMarketRequest addMarketIdsItem(String marketIdsItem) {
    if (this.marketIds == null) {
      this.marketIds = new ArrayList<String>();
    }
    this.marketIds.add(marketIdsItem);
    return this;
  }

   /**
   * The ids of the markets which should be deleted.
   * @return marketIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ids of the markets which should be deleted.")

  public List<String> getMarketIds() {
    return marketIds;
  }


  public void setMarketIds(List<String> marketIds) {
    this.marketIds = marketIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteMarketRequest deleteMarketRequest = (DeleteMarketRequest) o;
    return Objects.equals(this.marketIds, deleteMarketRequest.marketIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteMarketRequest {\n");
    sb.append("    marketIds: ").append(toIndentedString(marketIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

