/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.ErrorDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * GeoUpdateResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GeoUpdateResult {
  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private ErrorDescription error;

  public static final String SERIALIZED_NAME_RECORD = "record";
  @SerializedName(SERIALIZED_NAME_RECORD)
  private Map<String, Object> record = null;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<ErrorDescription> warnings = null;


  public GeoUpdateResult error(ErrorDescription error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ErrorDescription getError() {
    return error;
  }


  public void setError(ErrorDescription error) {
    this.error = error;
  }


  public GeoUpdateResult record(Map<String, Object> record) {
    
    this.record = record;
    return this;
  }

  public GeoUpdateResult putRecordItem(String key, Object recordItem) {
    if (this.record == null) {
      this.record = new HashMap<String, Object>();
    }
    this.record.put(key, recordItem);
    return this;
  }

   /**
   * The original input of the operation (will only be transmitted when the query parameter verbose&#x3D;true was added to the request).
   * @return record
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The original input of the operation (will only be transmitted when the query parameter verbose=true was added to the request).")

  public Map<String, Object> getRecord() {
    return record;
  }


  public void setRecord(Map<String, Object> record) {
    this.record = record;
  }


  public GeoUpdateResult success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * If true, the operation succeeded. Otherwise an error occurred which will be described in the error field.
   * @return success
  **/
  @ApiModelProperty(example = "true", required = true, value = "If true, the operation succeeded. Otherwise an error occurred which will be described in the error field.")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public GeoUpdateResult warnings(List<ErrorDescription> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public GeoUpdateResult addWarningsItem(ErrorDescription warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<ErrorDescription>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * A list of all warnings.
   * @return warnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of all warnings.")

  public List<ErrorDescription> getWarnings() {
    return warnings;
  }


  public void setWarnings(List<ErrorDescription> warnings) {
    this.warnings = warnings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoUpdateResult geoUpdateResult = (GeoUpdateResult) o;
    return Objects.equals(this.error, geoUpdateResult.error) &&
        Objects.equals(this.record, geoUpdateResult.record) &&
        Objects.equals(this.success, geoUpdateResult.success) &&
        Objects.equals(this.warnings, geoUpdateResult.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, record, success, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoUpdateResult {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    record: ").append(toIndentedString(record)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

