/*
 * FACT-Finder REST-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.factfinder.client.model.TypedFlatRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RecommendationResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RecommendationResult {
  public static final String SERIALIZED_NAME_HITS = "hits";
  @SerializedName(SERIALIZED_NAME_HITS)
  private List<TypedFlatRecord> hits = new ArrayList<TypedFlatRecord>();

  public static final String SERIALIZED_NAME_TIMED_OUT = "timedOut";
  @SerializedName(SERIALIZED_NAME_TIMED_OUT)
  private Boolean timedOut;


  public RecommendationResult hits(List<TypedFlatRecord> hits) {
    
    this.hits = hits;
    return this;
  }

  public RecommendationResult addHitsItem(TypedFlatRecord hitsItem) {
    this.hits.add(hitsItem);
    return this;
  }

   /**
   * Records of the recommended products.
   * @return hits
  **/
  @ApiModelProperty(required = true, value = "Records of the recommended products.")

  public List<TypedFlatRecord> getHits() {
    return hits;
  }


  public void setHits(List<TypedFlatRecord> hits) {
    this.hits = hits;
  }


  public RecommendationResult timedOut(Boolean timedOut) {
    
    this.timedOut = timedOut;
    return this;
  }

   /**
   * Set to true when a timeout occurs.
   * @return timedOut
  **/
  @ApiModelProperty(required = true, value = "Set to true when a timeout occurs.")

  public Boolean getTimedOut() {
    return timedOut;
  }


  public void setTimedOut(Boolean timedOut) {
    this.timedOut = timedOut;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationResult recommendationResult = (RecommendationResult) o;
    return Objects.equals(this.hits, recommendationResult.hits) &&
        Objects.equals(this.timedOut, recommendationResult.timedOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hits, timedOut);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationResult {\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    timedOut: ").append(toIndentedString(timedOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

