/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import de.factfinder.client.model.Filter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchLogEvent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T08:09:51.291+02:00")
public class SearchLogEvent {
  @SerializedName("additionalInfo")
  private String additionalInfo = null;

  @SerializedName("bestSimi")
  private Integer bestSimi = null;

  @SerializedName("cookieId")
  private String cookieId = null;

  @SerializedName("customSorting")
  private Boolean customSorting = null;

  @SerializedName("filters")
  private List<Filter> filters = new ArrayList<Filter>();

  @SerializedName("hitCount")
  private Integer hitCount = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("masterId")
  private String masterId = null;

  @SerializedName("minSimi")
  private Integer minSimi = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("query")
  private String query = null;

  @SerializedName("searchField")
  private String searchField = null;

  @SerializedName("searchTime")
  private Integer searchTime = null;

  @SerializedName("sid")
  private String sid = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("userId")
  private String userId = null;

  public SearchLogEvent additionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Get additionalInfo
   * @return additionalInfo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public SearchLogEvent bestSimi(Integer bestSimi) {
    this.bestSimi = bestSimi;
    return this;
  }

   /**
   * Get bestSimi
   * @return bestSimi
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getBestSimi() {
    return bestSimi;
  }

  public void setBestSimi(Integer bestSimi) {
    this.bestSimi = bestSimi;
  }

  public SearchLogEvent cookieId(String cookieId) {
    this.cookieId = cookieId;
    return this;
  }

   /**
   * Get cookieId
   * @return cookieId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCookieId() {
    return cookieId;
  }

  public void setCookieId(String cookieId) {
    this.cookieId = cookieId;
  }

  public SearchLogEvent customSorting(Boolean customSorting) {
    this.customSorting = customSorting;
    return this;
  }

   /**
   * Get customSorting
   * @return customSorting
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCustomSorting() {
    return customSorting;
  }

  public void setCustomSorting(Boolean customSorting) {
    this.customSorting = customSorting;
  }

  public SearchLogEvent filters(List<Filter> filters) {
    this.filters = filters;
    return this;
  }

  public SearchLogEvent addFiltersItem(Filter filtersItem) {
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<Filter> getFilters() {
    return filters;
  }

  public void setFilters(List<Filter> filters) {
    this.filters = filters;
  }

  public SearchLogEvent hitCount(Integer hitCount) {
    this.hitCount = hitCount;
    return this;
  }

   /**
   * Get hitCount
   * @return hitCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getHitCount() {
    return hitCount;
  }

  public void setHitCount(Integer hitCount) {
    this.hitCount = hitCount;
  }

  public SearchLogEvent id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SearchLogEvent masterId(String masterId) {
    this.masterId = masterId;
    return this;
  }

   /**
   * Get masterId
   * @return masterId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMasterId() {
    return masterId;
  }

  public void setMasterId(String masterId) {
    this.masterId = masterId;
  }

  public SearchLogEvent minSimi(Integer minSimi) {
    this.minSimi = minSimi;
    return this;
  }

   /**
   * Get minSimi
   * @return minSimi
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getMinSimi() {
    return minSimi;
  }

  public void setMinSimi(Integer minSimi) {
    this.minSimi = minSimi;
  }

  public SearchLogEvent page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public SearchLogEvent pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public SearchLogEvent query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public SearchLogEvent searchField(String searchField) {
    this.searchField = searchField;
    return this;
  }

   /**
   * Get searchField
   * @return searchField
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSearchField() {
    return searchField;
  }

  public void setSearchField(String searchField) {
    this.searchField = searchField;
  }

  public SearchLogEvent searchTime(Integer searchTime) {
    this.searchTime = searchTime;
    return this;
  }

   /**
   * Get searchTime
   * @return searchTime
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getSearchTime() {
    return searchTime;
  }

  public void setSearchTime(Integer searchTime) {
    this.searchTime = searchTime;
  }

  public SearchLogEvent sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public SearchLogEvent title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SearchLogEvent userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchLogEvent searchLogEvent = (SearchLogEvent) o;
    return Objects.equals(this.additionalInfo, searchLogEvent.additionalInfo) &&
        Objects.equals(this.bestSimi, searchLogEvent.bestSimi) &&
        Objects.equals(this.cookieId, searchLogEvent.cookieId) &&
        Objects.equals(this.customSorting, searchLogEvent.customSorting) &&
        Objects.equals(this.filters, searchLogEvent.filters) &&
        Objects.equals(this.hitCount, searchLogEvent.hitCount) &&
        Objects.equals(this.id, searchLogEvent.id) &&
        Objects.equals(this.masterId, searchLogEvent.masterId) &&
        Objects.equals(this.minSimi, searchLogEvent.minSimi) &&
        Objects.equals(this.page, searchLogEvent.page) &&
        Objects.equals(this.pageSize, searchLogEvent.pageSize) &&
        Objects.equals(this.query, searchLogEvent.query) &&
        Objects.equals(this.searchField, searchLogEvent.searchField) &&
        Objects.equals(this.searchTime, searchLogEvent.searchTime) &&
        Objects.equals(this.sid, searchLogEvent.sid) &&
        Objects.equals(this.title, searchLogEvent.title) &&
        Objects.equals(this.userId, searchLogEvent.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalInfo, bestSimi, cookieId, customSorting, filters, hitCount, id, masterId, minSimi, page, pageSize, query, searchField, searchTime, sid, title, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchLogEvent {\n");
    
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    bestSimi: ").append(toIndentedString(bestSimi)).append("\n");
    sb.append("    cookieId: ").append(toIndentedString(cookieId)).append("\n");
    sb.append("    customSorting: ").append(toIndentedString(customSorting)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    hitCount: ").append(toIndentedString(hitCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    masterId: ").append(toIndentedString(masterId)).append("\n");
    sb.append("    minSimi: ").append(toIndentedString(minSimi)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    searchField: ").append(toIndentedString(searchField)).append("\n");
    sb.append("    searchTime: ").append(toIndentedString(searchTime)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

