/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import de.factfinder.client.model.Params;
import de.factfinder.client.model.SearchControlParams;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SearchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T08:09:51.291+02:00")
public class SearchRequest {
  @SerializedName("params")
  private Params params = null;

  @SerializedName("searchControlParams")
  private SearchControlParams searchControlParams = null;

  @SerializedName("sid")
  private String sid = null;

  @SerializedName("userInput")
  private String userInput = null;

  public SearchRequest params(Params params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Params getParams() {
    return params;
  }

  public void setParams(Params params) {
    this.params = params;
  }

  public SearchRequest searchControlParams(SearchControlParams searchControlParams) {
    this.searchControlParams = searchControlParams;
    return this;
  }

   /**
   * Get searchControlParams
   * @return searchControlParams
  **/
  @ApiModelProperty(example = "null", value = "")
  public SearchControlParams getSearchControlParams() {
    return searchControlParams;
  }

  public void setSearchControlParams(SearchControlParams searchControlParams) {
    this.searchControlParams = searchControlParams;
  }

  public SearchRequest sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public SearchRequest userInput(String userInput) {
    this.userInput = userInput;
    return this;
  }

   /**
   * Get userInput
   * @return userInput
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserInput() {
    return userInput;
  }

  public void setUserInput(String userInput) {
    this.userInput = userInput;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequest searchRequest = (SearchRequest) o;
    return Objects.equals(this.params, searchRequest.params) &&
        Objects.equals(this.searchControlParams, searchRequest.searchControlParams) &&
        Objects.equals(this.sid, searchRequest.sid) &&
        Objects.equals(this.userInput, searchRequest.userInput);
  }

  @Override
  public int hashCode() {
    return Objects.hash(params, searchControlParams, sid, userInput);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequest {\n");
    
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    searchControlParams: ").append(toIndentedString(searchControlParams)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    userInput: ").append(toIndentedString(userInput)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

