/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.factfinder.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import de.factfinder.client.model.Params;
import de.factfinder.client.model.SearchRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SingleWordSearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-18T10:39:52.864+02:00")
public class SingleWordSearchResult {
  @SerializedName("previewRecords")
  private List<SearchRecord> previewRecords = new ArrayList<SearchRecord>();

  @SerializedName("recordCount")
  private Integer recordCount = null;

  @SerializedName("searchParams")
  private Params searchParams = null;

  @SerializedName("word")
  private String word = null;

  public SingleWordSearchResult previewRecords(List<SearchRecord> previewRecords) {
    this.previewRecords = previewRecords;
    return this;
  }

  public SingleWordSearchResult addPreviewRecordsItem(SearchRecord previewRecordsItem) {
    this.previewRecords.add(previewRecordsItem);
    return this;
  }

   /**
   * Get previewRecords
   * @return previewRecords
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<SearchRecord> getPreviewRecords() {
    return previewRecords;
  }

  public void setPreviewRecords(List<SearchRecord> previewRecords) {
    this.previewRecords = previewRecords;
  }

  public SingleWordSearchResult recordCount(Integer recordCount) {
    this.recordCount = recordCount;
    return this;
  }

   /**
   * Get recordCount
   * @return recordCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRecordCount() {
    return recordCount;
  }

  public void setRecordCount(Integer recordCount) {
    this.recordCount = recordCount;
  }

  public SingleWordSearchResult searchParams(Params searchParams) {
    this.searchParams = searchParams;
    return this;
  }

   /**
   * Get searchParams
   * @return searchParams
  **/
  @ApiModelProperty(example = "null", value = "")
  public Params getSearchParams() {
    return searchParams;
  }

  public void setSearchParams(Params searchParams) {
    this.searchParams = searchParams;
  }

  public SingleWordSearchResult word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingleWordSearchResult singleWordSearchResult = (SingleWordSearchResult) o;
    return Objects.equals(this.previewRecords, singleWordSearchResult.previewRecords) &&
        Objects.equals(this.recordCount, singleWordSearchResult.recordCount) &&
        Objects.equals(this.searchParams, singleWordSearchResult.searchParams) &&
        Objects.equals(this.word, singleWordSearchResult.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previewRecords, recordCount, searchParams, word);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleWordSearchResult {\n");
    
    sb.append("    previewRecords: ").append(toIndentedString(previewRecords)).append("\n");
    sb.append("    recordCount: ").append(toIndentedString(recordCount)).append("\n");
    sb.append("    searchParams: ").append(toIndentedString(searchParams)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

