/*
 * FACT-Finder REST-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiError;
import io.swagger.client.model.ResultSuggestion;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SuggestApi
 */
@Ignore
public class SuggestApiTest {

    private final SuggestApi api = new SuggestApi();

    
    /**
     * Get suggestions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSuggestionsUsingGETTest() throws ApiException {
        String channel = null;
        String query = null;
        List<ResultSuggestion> response = api.getSuggestionsUsingGET(channel, query);

        // TODO: test validations
    }
    
}
